In [1]:
import numpy as np
x = np.array([5, 8, 
              9, 10, 
              11]) # using 'array' method

type(x)   # Displays type of array 'x'

numpy.ndarray

In [2]:
x

array([ 5,  8,  9, 10, 11])

In [3]:
y = np.array([[6, 9, 5], 
              [10, 82, 34]])  
print(y)

[[ 6  9  5]
 [10 82 34]]


In [5]:
y.ndim

2

In [6]:
y.dtype

dtype('int64')

In [7]:
y.shape

(2, 3)

In [8]:
y.size

6

In [9]:
y.itemsize

8

In [10]:
y.nbytes

48

In [11]:
y

array([[ 6,  9,  5],
       [10, 82, 34]])

In [12]:
y.dtype

dtype('int64')

In [13]:
y2 = np.array([[6, 9, 5],
              [10, 82, 34]], 
             dtype='float64')  
print(y2)
print(y2.dtype)

[[ 6.  9.  5.]
 [10. 82. 34.]]
float64


In [15]:
y2.shape

(2, 3)

y2.flags

In [16]:
y2.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

In [17]:
import numpy as np

x = np.array([[3.2, 7.8, 9.2],
             [4.5, 9.1, 1.2]], dtype='int64')
print(x.itemsize)

8


In [19]:
import numpy as np
n = [5, 10, 15, 20, 25]
x=np.array(n)
x.dtype

dtype('int64')

In [21]:
x.ndim

1

In [25]:
x.shape

(5,)

In [26]:
x.size

5

In [27]:
m = [[-1, -2, -3, -4], [-2,-4, -6, -8]]

In [29]:
y=np.array(m)
y.dtype

dtype('int64')

In [31]:
y.ndim

2

In [32]:
y.shape

(2, 4)

In [33]:
y.size

8

In [34]:
y.itemsize

8

In [35]:
y.size

8

In [36]:
y.dtype

dtype('int64')

In [46]:
import numpy as np
a = [[[4.1, 2.5], [1.1, 2.3], [9.1, 2.5]], 
     [[8.6, 9.9],[3.6, 4.3], [6.6, 0.3]]]

x = np.array(a, dtype='float64')

type(x), x.ndim, x.shape, 

(numpy.ndarray, 3, (2, 3, 2))

In [47]:
x = np.zeros(shape=(2,4))
print(x)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [48]:
y = np.full(shape=(2,3), fill_value=10.5)
print(y)

[[10.5 10.5 10.5]
 [10.5 10.5 10.5]]


In [49]:
x1 = np.arange(3, 15, 2.5) # 2.5 is step
print(x1)

[ 3.   5.5  8.  10.5 13. ]


In [54]:
y11= np.linspace(1,55,5)
print(y11)

[ 1.  14.5 28.  41.5 55. ]


In [56]:
np.random.seed(100) # setting seed
x2 = np.random.rand(5) # 2 random numbers between 0 and 1

print(x2)

[0.54340494 0.27836939 0.42451759 0.84477613 0.00471886]


In [57]:
y = np.random.randint(10, 50, 3) # 3 random integers between 10 and 50

print(y)

[44 12 44]


In [58]:
np.random.seed(100)
x = np.random.randn(3) # Standard normal distribution

print(x)

[-1.74976547  0.3426804   1.1530358 ]


In [61]:
np.random.seed(100)
x = 10 + 2*np.random.randn(3) # normal distribution with mean 10 and sd 2

print(x)

[ 6.50046905 10.68536081 12.30607161]


In [62]:
x = 10 + 2*np.random.randn(3) # normal distribution with mean 10 and sd 2

print(x)

[ 9.49512793 11.96264157 11.02843768]


In [63]:
from io import StringIO
import numpy as np

x = StringIO('''88.25 93.45 72.60 90.90
72.3 78.85 92.15 65.75
90.5 92.45 89.25 94.50
''')

d = np.loadtxt(x,delimiter=' ')

print(d)

print(d.ndim, d.shape)

[[88.25 93.45 72.6  90.9 ]
 [72.3  78.85 92.15 65.75]
 [90.5  92.45 89.25 94.5 ]]
2 (3, 4)


In [69]:
z = np.eye(2)
print(z)

[[1. 0.]
 [0. 1.]]


In [71]:
print(np.array(([1, 2], (3,4))).shape)

(2, 2)


In [72]:
import numpy as np

x = np.array([[-1,0,1], [-2, 0, 2]])

y = np.zeros_like(x)
print(y)

[[0 0 0]
 [0 0 0]]


In [79]:
x3=np.array([[[-1,1],[-2,2]],[[-3, 3], [-4, 4]]])

In [80]:
x3.dtype

dtype('int64')

In [81]:
x3.ndim

3

In [82]:
x3.shape

(2, 2, 2)

In [83]:
x3.size

8

In [84]:
x3.itemsize

8

In [85]:
x4=np.full(shape=(3,2,2), fill_value=1)
print(x4)

[[[1 1]
  [1 1]]

 [[1 1]
  [1 1]]

 [[1 1]
  [1 1]]]


In [87]:
x5=np.eye(3, k=0)
print(x5)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [91]:
x4=np.random.rand(24).reshape(3, 4,2)
print(x4)

[[[0.10837689 0.21969749]
  [0.97862378 0.81168315]
  [0.17194101 0.81622475]
  [0.27407375 0.43170418]]

 [[0.94002982 0.81764938]
  [0.33611195 0.17541045]
  [0.37283205 0.00568851]
  [0.25242635 0.79566251]]

 [[0.01525497 0.59884338]
  [0.60380454 0.10514769]
  [0.38194344 0.03647606]
  [0.89041156 0.98092086]]]


In [94]:
x5=5+2.5*np.random.randn(20)
print(x5)

[ 8.91794696  6.24256179  7.88968084  9.59652919  8.83931654  5.63749432
  2.88960687  2.54264136  4.23475542  7.09625153  0.7728796   7.87793414
  2.42665788  3.72251953 -0.90067634  5.25898783  9.34704432  8.10468961
  5.33103189  6.44448489]


In [101]:
x6=np.arange(2,42,2)
x6

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40])

In [102]:
x7=np.linspace(10,20,30)
x7

array([10.        , 10.34482759, 10.68965517, 11.03448276, 11.37931034,
       11.72413793, 12.06896552, 12.4137931 , 12.75862069, 13.10344828,
       13.44827586, 13.79310345, 14.13793103, 14.48275862, 14.82758621,
       15.17241379, 15.51724138, 15.86206897, 16.20689655, 16.55172414,
       16.89655172, 17.24137931, 17.5862069 , 17.93103448, 18.27586207,
       18.62068966, 18.96551724, 19.31034483, 19.65517241, 20.        ])

In [103]:
import numpy as np
np.random.seed(100)
x = np.random.randint(10, 100, 8)
print(x, end='\n\n')
y = x.reshape(2,4)
print(y, end='\n\n')
z = x.reshape(2,2,2)
print(z, '\n\n')

[18 34 77 97 89 58 20 62]

[[18 34 77 97]
 [89 58 20 62]]

[[[18 34]
  [77 97]]

 [[89 58]
  [20 62]]] 




In [104]:
import numpy as np
x = np.array([[-1, 1], [-3, 3]])
y = np.array([[-2, 2], [-4, 4]])
np.vstack((x,y))

array([[-1,  1],
       [-3,  3],
       [-2,  2],
       [-4,  4]])

In [105]:
import numpy as np
x = np.array([[-1, 1], [-3, 3]])
y = np.array([[-2, 2], [-4, 4]])
z = np.array([[-5, 5], [-6, 6]])
np.hstack((x,y,z))

array([[-1,  1, -2,  2, -5,  5],
       [-3,  3, -4,  4, -6,  6]])

In [106]:
import numpy as np
x = np.arange(30).reshape(6, 5)
res = np.vsplit(x, 2)
print(res[0], end='\n\n')
print(res[1])

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]

[[15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]]


In [107]:
import numpy as np
x = np.arange(10).reshape(2, 5)
res = np.hsplit(x, (2,4))
print(res[0], end='\n\n')
print(res[1], end='\n\n')
print(res[2])

[[0 1]
 [5 6]]

[[2 3]
 [7 8]]

[[4]
 [9]]


In [108]:
print(res[0][0], end='\n\n')

[0 1]



In [109]:
print(res[0][1], end='\n\n')

[5 6]



In [110]:
import numpy as np

x = np.arange(20).reshape(10, 10)
x

ValueError: cannot reshape array of size 20 into shape (10,10)

In [113]:
import numpy as np

x = np.arange(90).reshape(3, 15, 2)
x[1]

array([[30, 31],
       [32, 33],
       [34, 35],
       [36, 37],
       [38, 39],
       [40, 41],
       [42, 43],
       [44, 45],
       [46, 47],
       [48, 49],
       [50, 51],
       [52, 53],
       [54, 55],
       [56, 57],
       [58, 59]])

In [118]:
import numpy as np

x = np.arange(20).reshape(4, 5)
x.shape
print(x)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [123]:
import numpy as np

x = np.arange(20)
print(x.shape)
y=x.reshape(2,10)
res = np.hsplit(y, (2))
print(res[0])
print(res[1])

(20,)
[[ 0  1  2  3  4]
 [10 11 12 13 14]]
[[ 5  6  7  8  9]
 [15 16 17 18 19]]


In [125]:
z=x.reshape(4,5)
resz=np.vsplit(z,2)
print(resz[0])
print(resz[1])

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[10 11 12 13 14]
 [15 16 17 18 19]]


In [128]:
p=np.array([3, 6, 9, 12]).reshape(2,2)
q=np.array([15, 18, 21, 24, 27, 30]).reshape(2,3)
np.hstack((p,q))

array([[ 3,  6, 15, 18, 21],
       [ 9, 12, 24, 27, 30]])

In [1]:
import numpy as np
x = np.arange(6).reshape(2,3)
print(x + 10, end='\n\n')
print(x * 3, end='\n\n')
print(x % 2)

[[10 11 12]
 [13 14 15]]

[[ 0  3  6]
 [ 9 12 15]]

[[0 1 0]
 [1 0 1]]


In [2]:
import numpy as np
x = np.array([[-1, 1], [-2, 2]])
y = np.array([[4, -4], [5, -5]])
print(x + y, end='\n\n')
print(x * y)

[[ 3 -3]
 [ 3 -3]]

[[ -4  -4]
 [-10 -10]]


In [3]:
import numpy as np
x = np.array([[-1, 1], [-2, 2]])
y = np.array([-10, 10])
print(x * y)

[[10 10]
 [20 20]]


In [5]:
import numpy as np
x = np.array([[0,1], [2,3]])
print(np.square(x), end='\n\n')
print(np.sin(x))

[[0 1]
 [4 9]]

[[0.         0.84147098]
 [0.90929743 0.14112001]]


In [8]:
import numpy as np
x = np.array([[0,1], [2, 3]])
print(x.sum(), end='\n\n')
print(x.sum(axis=0), end='\n\n')
print(x.sum(axis=1))

6

[2 4]

[1 5]


In [10]:
import numpy as np

x = np.arange(20).reshape(4,5)
print(x)
print(x.mean(axis=1))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
[ 2.  7. 12. 17.]


In [14]:
import numpy as np

x = np.arange(30).reshape(5,6)
print(x)
print(x.argmax(axis=1))
print(x.argmax(axis=0))

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]
[5 5 5 5 5]
[4 4 4 4 4 4]


In [15]:
import numpy as np

x = np.arange(4).reshape(2,2)
print(x)
print(np.isfinite(x))

[[0 1]
 [2 3]]
[[ True  True]
 [ True  True]]


In [16]:
import numpy as np

print(np.repeat(3, 4))

[3 3 3 3]


In [19]:
import numpy as np
y = np.arange(6).reshape(2,3)
print(np.square(y))
print(np.square(y)+5)

[[ 0  1  4]
 [ 9 16 25]]
[[ 5  6  9]
 [14 21 30]]


In [25]:
import numpy as np
y = np.random.randint(-30,30,30).reshape(5,6)
print(y)
print(y.sum(axis=0))
print(y.sum(axis=1))

[[-18 -26   7 -25  17  26]
 [  1   3   9   0  -3  20]
 [-14  23  25 -29  29   9]
 [ 29  10  22  -8  21 -15]
 [-16  17   1  25  19   1]]
[-18  27  64 -37  83  41]
[-19  30  43  59  47]


In [33]:
import numpy as np
x = 10+2*np.random.rand(50)
print(x)
print(x.mean())
print(x.std())
print(x.var())

[11.04041468 10.16185054 11.55836042 11.56409796 10.02690191 10.20265994
 11.14422087 10.28870578 11.88556178 11.01583604 10.73453726 10.56710115
 11.26665136 10.68035422 10.19034372 10.66366081 10.08944445 10.80241613
 10.07313497 11.4671186  11.01290065 10.16715457 11.69556109 10.83117622
 10.21618635 11.21456263 10.8127965  11.54980846 10.15710729 10.48239617
 11.85811541 11.1368819  11.7674728  11.79728646 10.51106265 11.78688618
 11.24645108 10.14632311 10.34572177 11.4510926  11.57794234 11.4023316
 10.62904223 10.11206579 10.89445945 10.17321149 11.81582996 10.35937953
 11.12774678 10.08821707]
10.875810854392267
0.6013930482017269
0.3616735984253646


In [34]:
x = np.array([5, 10, 15, 20, 25, 30, 35])
print(x[1])  # Indexing
print(x[1:6]) # Slicing
print(x[1:6:3]) # Slicing

10
[10 15 20 25 30]
[10 25]


In [35]:
#ARRAY-INDEXING

In [36]:
import numpy as np
y = np.array([[0, 1, 2],
              [3, 4, 5]])
print(y[1:2, 1:3]) 
print(y[1])   
print(y[:, 1]) 

[[4 5]]
[3 4 5]
[1 4]


In [42]:
x=np.arange(90).reshape(9,10)
print(x[4,5])
print(x[5,4])

In [57]:
z = np.array([[[-1, 1], [-2, 2]],
              [[-4, 4], [-5, 5]],
              [[-7, 7], [-9, 9]]])
print(z.shape)
print(z[1,:,1]) # index 1 element in row of index 1
print(z[1:,1,:]) # From all outer rows except the first, select 1st index element (which itself is an array) completely.
print(z[2]) # print 2nd index element

#print(z[2,1])
#print(z[1,:,1])
print(z[0])
print(z[1])
print(z[2])

(3, 2, 2)
[4 5]
[[-5  5]
 [-9  9]]
[[-7  7]
 [-9  9]]
[[-1  1]
 [-2  2]]
[[-4  4]
 [-5  5]]
[[-7  7]
 [-9  9]]


In [58]:
x = np.array([[-1, 1], [-2, 2]])
for row in x:
    print('Row :',row)

Row : [-1  1]
Row : [-2  2]


In [59]:
import numpy as np
x = np.array([[0,1], [2, 3]])
for a in np.nditer(x):
    print(a)

0
1
2
3


In [60]:
import numpy as np
x = np.arange(10).reshape(2,5)
condition = x % 2 == 0
print(condition)
print(x[condition])

[[ True False  True False  True]
 [False  True False  True False]]
[0 2 4 6 8]


In [64]:
import numpy as np

x = np.arange(30).reshape(3,5,2)
print(x)
print(x[1,::2,1])

[[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]
  [ 8  9]]

 [[10 11]
  [12 13]
  [14 15]
  [16 17]
  [18 19]]

 [[20 21]
  [22 23]
  [24 25]
  [26 27]
  [28 29]]]
[11 15 19]


In [73]:
import numpy as np

x = np.array([[0, 1], [1, 1], [2, 2]])
y = x.sum(-1)
print(x)
print(y)
print(x[y < 2, :])

[[0 1]
 [1 1]
 [2 2]]
[1 2 4]
[[0 1]]


In [76]:
import numpy as np

x = np.arange(12).reshape(3,4)
x
print(x[:,1])

[1 5 9]


In [78]:
import numpy as np

x = np.arange(12).reshape(3,4)
x
print(x[-1:,].shape)

(1, 4)


In [80]:
import numpy as np

x = np.arange(12).reshape(3,4)
x
print(x[-2])

[4 5 6 7]


In [91]:
x=np.arange(30).reshape(6,5)
print(x[-1])
print(x)
print(x[:,2:3])
print(x[0:2,2:])

[25 26 27 28 29]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]]
[[ 2]
 [ 7]
 [12]
 [17]
 [22]
 [27]]
[[2 3 4]
 [7 8 9]]


In [95]:
x=np.arange(30).reshape(2,3,5)
b=[True,False]
print(x[b])
x[b,:,1:3]

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]]


array([[[ 1,  2],
        [ 6,  7],
        [11, 12]]])

In [96]:
import numpy as np

x = np.arange(12).reshape(3,4)
print(x[-1:,].shape)

(1, 4)


In [97]:
import numpy as np

x = np.arange(4).reshape(2,2)
print(x.tolist())

[[0, 1], [2, 3]]


In [98]:
import numpy as np

x = np.arange(4)
print(x**2)

[0 1 4 9]


In [99]:
import numpy as np

x = np.arange(12).reshape(3,4)
print(x[:,1])

[1 5 9]


In [101]:
import numpy as np

x = np.arange(6).reshape(2,3)

y = np.hsplit(x,(2,))
print(y[0])
y

[[0 1]
 [3 4]]


[array([[0, 1],
        [3, 4]]), array([[2],
        [5]])]

In [102]:
import numpy as np

print(np.repeat(3, 4))

[3 3 3 3]


In [106]:
import numpy as np

x = np.arange(30).reshape(3,5,2)
x
print(x[-1, 2:-1, -1])

[25 27]


In [107]:
import numpy as np

x = np.arange(20).reshape(10, 10)

ValueError: cannot reshape array of size 20 into shape (10,10)

In [109]:
import numpy as np

x = np.arange(30).reshape(3,5,2)
x
print(x[1,::2,1])

[11 15 19]


In [111]:
import numpy as np

x = np.arange(12).reshape(3,4)
print(x[-2])
x

[4 5 6 7]


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [112]:
np.random.rand(3, 2)

array([[0.34810977, 0.3682033 ],
       [0.08309928, 0.01617996],
       [0.29461189, 0.60145616]])

In [113]:
np.random.random(3, 2)

TypeError: random() takes at most 1 positional argument (2 given)

In [114]:
import numpy as np

x = np.arange(4)
y = np.arange(4)

print(x == y)

[ True  True  True  True]


In [115]:
import numpy as np

print(np.array(([1, 2], (3,4))).shape)

(2, 2)


In [116]:
%history

import numpy as np
x = np.arange(6).reshape(2,3)
print(x + 10, end='\n\n')
print(x * 3, end='\n\n')
print(x % 2)
import numpy as np
x = np.array([[-1, 1], [-2, 2]])
y = np.array([[4, -4], [5, -5]])
print(x + y, end='\n\n')
print(x * y)
import numpy as np
x = np.array([[-1, 1], [-2, 2]])
y = np.array([-10, 10])
print(x * y)
s1 = (4, 3); s2 = (3,)
import numpy as np
x = np.array([[0,1], [2,3]])
print(np.square(x), end='\n\n')
print(np.sin(x))
import numpy as np
x = np.array([[0,1], [2, 3]])
print(x.sum(), end='\n\n')
print(x.sum(axis=0), end='\n\n')
print(x.sum(axis=1))
import numpy as np
x = np.array([[0,1], [2, 3]])
print(x.sum(), end='\n\n')
print(x.sum(axis=0), end='\n\n')
print(x.sum(axis=2))
import numpy as np
x = np.array([[0,1], [2, 3]])
print(x.sum(), end='\n\n')
print(x.sum(axis=0), end='\n\n')
print(x.sum(axis=1))
import numpy as np

x = np.arange(20).reshape(4,5)
print(x.mean(axis=1))
import numpy as np

x = np.arange(20).reshape(4,5)
print(x)
print(x.mean(axis=1))
import num